version: "3.9"

services:
  dev-env:
    build: .
    container_name: dev-container
    ports:
      - "4200:4200"
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./projetos:/home/devuser/projetos
    tty: true
